### ISSUE TITLE
Access denied for documentation on http://oscf.org.uk/dart/api/sporran

### ISSUE THREAD

**Issue by kpmy** [shamblett/sporran#12]
Hi. 
There is a trouble when accessing documentation site, browser asks me for login/password. Is it possible to fix this behaviour of site, or just place documentation to another place.

**Comment by shamblett** [comment]
Hi,

Yes, I need to update this, the docs are in dartdocs(where all the pub
packages are), try here

http://www.dartdocs.org/documentation/sporran/2.1.0/index.html#sporran

Steve

On 17 March 2015 at 13:13, Пётр <notifications@github.com> wrote:

> Hi.
> There is a trouble when accessing documentation site, browser asks me for
> login/password. Is it possible to fix this behaviour of site, or just place
> documentation to another place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shamblett/sporran/issues/12>.
>



-- 
"Talk is cheap. Show me the code."
- Linus Torvalds

Steve Hamblett

**Comment by kpmy** [comment]
Oh, thanks a lot!
