### ISSUE TITLE
Package this project as a library for existing Android app

### ISSUE THREAD

**Issue by skyred** [shamblett/sporran#19]
couchbase-lite-android 2.0 has dropped the support for syncing with CouchDB. I was wondering if we can take advantage of [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) to package this project as a library not only for flutter but also for existing android apps written mostly in Java.

**Comment by shamblett** [comment]
I don't know much about flutter and even less about android but reading the link above it does seem to suggest this is possible. At the end of the day sporran is just a standard Dart package which you can do with whatever the Google guys support, the package itself doesn't preclude any of this.
