### ISSUE TITLE
Replication from/to couchDb

### ISSUE THREAD

**Issue by daw415** [shamblett/sporran#20]
Hello,

I would like define whata data should be send to cuchDb like this in ionic :

this.db.replicate.to(this.remote, optionsTo)
this.db.replicate.from(this.remote, this.optionsFrom)
let optionsTo = {
      live: true,
      retry: true,
      continuous: true,
      filter: function (doc) {
          return doc._id.startsWith("ImportantData")
      }
    };

It is possible in sporran ?

**Comment by shamblett** [comment]
Sporran is built on [Wilt](https://pub.dev/packages/wilt) which is the couchdb interface, Wilt has a 'updateChangeNotificationParameters' method where you can change database sync parameters however you need to check if it will do what you need above.

**Comment by daw415** [comment]
Thanks for answer.

In method 'updateChangeNotificationParameters' I can't see options for filter which data should bee synch.

I conclude that at the moment it's impossible in sporran / wilt.

Well, shame.
